(function(){
'use strict';
const T=window.Training,C=window.TrainingCore,G=window.ExerciseGuides,$=id=>document.getElementById(id);
const KEY='bigthree500.training.v2', names={sq:'스쿼트',bp:'벤치',dl:'데드리프트'}, colors={sq:'var(--p25)',bp:'var(--p20)',dl:'var(--p15)'};
const today=()=>C.iso(new Date());
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let data={version:2,sessions:{},measurements:[],postponed:{},bar:20}, active=null, selected=null, selectedWeek=null, testLift=null, timerEnd=null, pausedSeconds=null;
try{const saved=JSON.parse(localStorage.getItem(KEY)||'null');if(saved&&saved.version===2&&saved.sessions&&Array.isArray(saved.measurements)) data={...data,...saved};}catch(e){status('저장된 기록을 읽지 못했습니다. 이 화면의 새 기록은 저장 전까지 유지됩니다.',true);}
function status(message,error=false){$('save-status').textContent=message;$('save-status').classList.toggle('failure',error);}
function save(){try{localStorage.setItem(KEY,JSON.stringify(data));status('이 기기에 저장됨 · 다른 기기와 자동 동기화되지 않습니다.');return true;}catch(e){status('저장 공간에 기록하지 못했습니다. 창을 닫기 전에 기록을 백업하세요.',true);return false;}}
function weekInfo(){const w=T.state.week;const mon=C.add(T.state.start,(w-1)*7);return {w,mon,wib:(w-1)%4+1,wave:T.wave[(w-1)%4]};}
function exercises(day){
const expanded=[];
for(const e of T.days[day].ex){
if(e.n==='삼두 + 후면 삼각근'){expanded.push({...e,n:'삼두 푸시다운'},{...e,n:'리버스 플라이'});}
else if(e.n==='컬, 케이블 로우, 복근'){for(const n of ['덤벨 컬','케이블 로우','케이블 크런치'])expanded.push({...e,n});}
else if(e.n==='인클라인 / 스포토 프레스')expanded.push({...e,n:'인클라인 프레스',alternate:'스포토 프레스'});
else expanded.push({...e});
}return expanded;
}
function sessionAt(day,date){return data.sessions[`${date}:${day}`];}
function pickDay(){const info=weekInfo();if(selectedWeek!==info.w){selected=null;selectedWeek=info.w;}
if(selected!==null)return selected;
const current=today();let i=T.days.findIndex(d=>C.add(info.mon,d.dow)>=current&&!sessionAt(T.days.indexOf(d),C.add(info.mon,d.dow))?.completed);
if(i<0)i=T.days.findIndex((d,idx)=>!sessionAt(idx,C.add(info.mon,d.dow))?.completed);
return i<0?0:i;
}
function renderToday(){
const info=weekInfo(),idx=pickDay(),day=T.days[idx],date=C.add(info.mon,day.dow),first=exercises(idx)[0],p=C.prescription(first,info.wave,info.wib,T.read()),s=sessionAt(idx,date);
const dayNames=['월','화','수','목','금','토','일'];
const isToday=date===today(),past=date<today(),complete=s?.completed;
$('today').innerHTML=`<div class="today-top"><span>${today().replaceAll('-','.')} · ${info.w}주차</span><button class="ghost" data-action="current-week">이번 주</button></div>
<div class="today-card" style="--session-color:${colors[day.mc]||'var(--ink)'}"><div class="helper">${complete?'완료한 세션':isToday?'오늘의 운동':past?'선택한 세션':'다음 운동'} · ${date.replaceAll('-','.')} (${dayNames[day.dow]})</div><h1>${day.name}</h1><div class="lead-weight">${p.kg??'—'}<small>kg · ${p.sets}세트 × ${p.reps}회</small></div><p>${!isToday&&!past?'오늘은 예정된 훈련일이 아닙니다. 다음 세션을 미리 확인하거나 운동일을 바꿀 수 있어요.':`${first.n}부터 시작 · ${exercises(idx).length}개 운동 · ${info.wib===4?'회복 주차':'본세트 사이 휴식 3분'}`}</p><div class="actions"><button class="primary" data-action="start" data-day="${idx}">${s?'기록 이어보기':'운동 시작'}</button><button class="ghost" data-guide="${first.n}">동작 배우기</button></div></div>
<div class="day-picker" aria-label="세션 선택">${T.days.map((d,i)=>`<button data-action="pick-day" data-day="${i}" aria-pressed="${i===idx}">${dayNames[d.dow]} · ${sessionAt(i,C.add(info.mon,d.dow))?.completed?'완료':d.mc?names[d.mc]:'보조'}</button>`).join('')}</div><div id="session-editor" class="session-editor"></div>`;
if(active) renderSession();
}
function startSession(idx){
const info=weekInfo(),date=C.add(info.mon,T.days[idx].dow),key=`${date}:${idx}`;
if(!data.sessions[key]){data.sessions[key]={date,day:idx,week:info.w,completed:false,startedAt:Date.now(),exercises:exercises(idx).map(e=>{const p=C.prescription(e,info.wave,info.wib,T.read());return {name:e.n,alternate:e.alternate||null,main:e.main||null,kg:p.kg,sets:p.sets,reps:p.reps,warm:{},rows:Array.from({length:p.sets},()=>({kg:p.kg??'',reps:p.reps,rpe:'',done:false}))};})};save();}
active=key;renderSession();renderLog();$('session-editor').scrollIntoView({block:'start'});
}
function unitFor(name){return name==='중량 턱걸이'?'추가 중량 · 맨몸은 0kg':name.includes('덤벨')||name==='불가리안 스플릿 스쿼트'?'덤벨 한 손 기준':name==='앱 롤아웃'?'추가 중량 · 맨몸은 0kg':'바벨은 바 포함 총중량 · 기계는 표시 중량';}
function plateText(kg){if(kg===null||kg==='')return '';const result=C.plates(Number(kg),data.bar);if(result.remainder<0)return `${data.bar}kg 바보다 가벼움 · 가벼운 바/덤벨로 조정`;return `${data.bar}kg 바 · 한쪽 ${result.plates.length?result.plates.join(' + ')+'kg':'원판 없음'}${result.remainder>0?' · 사용 원판으로 정확히 구성 불가':''}`;}
function previous(name,s){const all=Object.values(data.sessions).filter(x=>x!==s&&x.date<=s.date).sort((a,b)=>b.date.localeCompare(a.date)||b.startedAt-a.startedAt);for(const last of all){const e=last.exercises.find(x=>x.name===name&&x.rows.some(r=>r.done));if(e){const rows=e.rows.filter(r=>r.done);return `${last.date} · ${rows.map(r=>`${r.kg}kg × ${r.reps}`).join(', ')}`;}}return '이전 기록 없음 · 이번 세션부터 쌓입니다.';}
function isBarbell(name){return !['중량 턱걸이','앱 롤아웃','레그컬','페이스풀','랫풀다운','삼두 푸시다운','리버스 플라이','불가리안 스플릿 스쿼트','덤벨 컬','케이블 로우','케이블 크런치'].includes(name);}
function warmupHTML(e,ei){
const barbell=isBarbell(e.name);
const work=Number(e.kg),rows=barbell&&e.kg!==null?C.warmup(work,data.bar,e.name==='데드리프트'||e.name==='데피싯 데드리프트'):work>0&&!['중량 턱걸이','앱 롤아웃'].includes(e.name)?[.5,.75].map((ratio,i)=>({kg:Math.floor(work*ratio*2)/2,reps:i?4:8,sets:1,rest:60})).filter((r,i,a)=>r.kg>0&&r.kg<work&&(!i||r.kg>a[i-1].kg)):[];
return `<div class="warmup"><h3>웜업 <span class="helper">본세트에 포함하지 않아요</span></h3>${rows.length?rows.map((r,i)=>`<div class="warmup-row"><input type="checkbox" id="warm-${ei}-${i}" data-warm="${ei}:${i}" ${e.warm?.[i]?'checked':''}><label for="warm-${ei}-${i}">${r.kg}kg × ${r.reps}회 × ${r.sets}세트</label><small>휴식 ${r.rest}초</small></div>`).join(''):`<p>${barbell?'가벼운 바 또는 맨몸으로 동작 연습 5~8회 × 1~2세트. 본중량 이하에서 준비하세요.':'가벼운 무게 또는 보조를 사용해 8~10회 × 1~2세트. 계획 중량을 입력하면 덤벨·기계 웜업 무게도 계산됩니다.'}</p>`}<p>${rows.length?'마지막 웜업 뒤 2~3분 쉬고 본세트로 넘어갑니다. ':''}${e.name.includes('데드리프트')?'바닥에서 시작할 때는 가벼운 원판도 받침으로 바 높이를 맞추세요. ':''}무게와 세트는 기본 예시입니다. 기계·덤벨은 사용 가능한 가까운 중량으로 맞추세요. 준비가 덜 됐으면 가벼운 연습 세트를 추가하세요.</p></div>`;
}
function renderSession(){
const host=$('session-editor');if(!host||!active)return;const s=data.sessions[active];if(!s){active=null;return;}
const count=s.exercises.reduce((n,e)=>n+e.rows.filter(r=>r.done).length,0),all=s.exercises.reduce((n,e)=>n+e.rows.length,0);
host.innerHTML=`<div class="session-top"><h2 style="font-size:24px;margin:0">${s.completed?'완료한 운동':'세션 기록'} <span class="helper" id="session-count">${count} / ${all}세트</span></h2><button class="ghost" data-action="close-session">접기</button><label>실제 운동일 <input type="date" id="session-date" value="${s.date}" max="${today()}"></label><label>바 무게 <select id="bar-weight"><option value="20" ${data.bar===20?'selected':''}>20kg</option><option value="15" ${data.bar===15?'selected':''}>15kg</option></select></label></div>
<p class="session-note">가벼운 걷기·사이클 5분 후 사용할 관절을 편하게 움직이세요. RPE 8 = 약 2회 여유, 9 = 약 1회 여유. 낯선 동작은 ‘동작 배우기’부터 확인하세요.</p>
${s.exercises.map((e,ei)=>`<details class="exercise" ${ei===0?'open':''}><summary><strong>${e.name}</strong><span>${e.kg===null?'중량 선택':e.kg+'kg'} · ${e.sets} × ${e.reps}</span></summary><div class="exercise-content"><div class="exercise-meta"><label class="helper">계획 중량 <input aria-label="${e.name} 계획 중량" data-work="${ei}" type="number" min="0" max="500" step="0.5" value="${e.kg??''}" style="width:94px"> kg</label><button class="ghost" data-guide="${e.name}">동작 배우기</button>${e.alternate?`<button class="ghost" data-action="alternate" data-ex="${ei}">${e.alternate}로 변경</button>`:''}</div><div class="weight-unit">${unitFor(e.name)}${e.name==='불가리안 스플릿 스쿼트'?' · 횟수는 한쪽 기준':''}</div>${e.kg!==null&&isBarbell(e.name)?`<p class="helper">${plateText(e.kg)}</p>`:''}${warmupHTML(e,ei)}<div class="previous">지난 운동: ${esc(previous(e.name,s))}</div><div class="set-head"><span>세트</span><span>실제 kg</span><span>횟수</span><span>RPE</span><span>완료</span></div>${e.rows.map((r,ri)=>`<div class="set-row"><span class="set-num">${ri+1}</span><input aria-label="${e.name} ${ri+1}세트 중량" type="number" min="0" max="500" step="0.5" data-row="${ei}:${ri}:kg" value="${r.kg}"><input aria-label="${e.name} ${ri+1}세트 횟수" type="number" min="1" max="50" step="1" data-row="${ei}:${ri}:reps" value="${r.reps}"><input aria-label="${e.name} ${ri+1}세트 RPE" type="number" min="1" max="10" step="0.5" placeholder="8" data-row="${ei}:${ri}:rpe" value="${r.rpe}"><input type="checkbox" aria-label="${e.name} ${ri+1}세트 완료" data-done="${ei}:${ri}" ${r.done?'checked':''}></div>`).join('')}<button class="ghost" data-action="timer" data-seconds="${e.main?180:90}">휴식 ${e.main?'3분':'90초'} 시작</button></div></details>`).join('')}<div class="actions"><button class="primary" data-action="finish">${s.completed?'완료 기록 저장':'운동 완료'}</button><button class="ghost" data-action="backup">기록 백업</button></div><p class="helper" id="session-feedback">세트별 중량·횟수·RPE와 완료 체크가 자동 저장됩니다.</p>`;
}
function latest(k){return data.measurements.filter(x=>x.lift===k).sort((a,b)=>b.date.localeCompare(a.date)||b.createdAt-a.createdAt)[0];}
function renderAssessment(){
$('assessment').innerHTML=`<h2>다음 1RM 점검</h2><p>기록 확인은 8주 간격이 기본입니다. 매번 최대 중량을 들 필요는 없어요.</p>${Object.keys(names).map(k=>{const m=latest(k),d=C.due(m?.date,today(),data.postponed[k]);return `<div class="test-row"><div><strong>${names[k]}</strong><small>${m?`${m.date} · ${m.kind==='actual'?'실측 1RM':'추정 e1RM'} ${m.value}kg`:'측정일 미등록 · 현재 값은 확인 전 기준값'}</small><span class="due">${d.unknown&&!data.postponed[k]?'첫 주에 기준 확인':`${d.date.replaceAll('-','.')} · ${d.days<0?Math.abs(d.days)+'일 경과':d.days===0?'오늘 점검':d.days+'일 남음'}`}</span></div><button class="ghost" data-action="test" data-lift="${k}">기록 / 점검</button></div>`;}).join('')}<div id="test-editor"></div><details class="plan-detail"><summary>언제 재고, 언제 미뤄야 하나요?</summary><p>마지막 기록 후 8주에 3~5회 세트로 추세를 확인하는 것이 이 앱의 기본 계획입니다. 첫 측정일을 모르면 지금 가진 기록의 날짜부터 등록하세요. 8주는 개인별 검사 의무나 목표 달성 보장이 아닙니다.</p><p>동일 종목의 목표 횟수를 두 번 연속 놓쳤다면 무게를 더하지 말고 피로·자세를 먼저 점검하세요. 통증, 컨디션 저하, 최근의 무거운 훈련이 남아 있으면 일정을 미루고 회복한 다음 진행합니다.</p><p>실제 1RM은 동작이 익숙하고 안전바·보조자 등 준비가 된 날 별도로 계획하세요. 첫 동작 학습일에 최대 중량을 시도하지 않습니다.</p><a href="https://www.hprc-online.org/physical-fitness/training-performance/what-one-rep-max" target="_blank" rel="noopener noreferrer">HPRC · 1RM과 반복 측정 안내</a></details>`;
if(testLift)renderTest();
}
function renderTest(){
const k=testLift;if(!k)return;const d=C.due(latest(k)?.date,today(),data.postponed[k]);
$('test-editor').innerHTML=`<form id="test-form" class="test-form"><h3>${names[k]} 기록 등록</h3><div class="form-grid"><label>측정 방식<select id="test-kind"><option value="estimate">3~5회로 추정 e1RM</option><option value="actual">실제로 성공한 1RM</option></select></label><label>실제 측정일<input id="test-date" type="date" value="${today()}" max="${today()}" required></label><label>성공한 중량 (kg)<input id="test-kg" type="number" min="1" max="500" step="0.5" placeholder="예: 100" required></label><label id="reps-label">성공한 반복 횟수<select id="test-reps"><option value="3">3회</option><option value="4">4회</option><option value="5">5회</option></select></label></div><output id="test-result">중량을 입력하세요</output><p id="test-explanation">Epley: 중량 × (1 + 횟수 ÷ 30). 여유를 남긴 세트에서는 실제 최대치보다 낮을 수 있습니다. 공식의 결과는 추정치이며 정확한 오차를 보장하지 않습니다.</p><label class="check-label"><input id="test-form-check" type="checkbox" required>통증 없이 일정한 자세로 수행한 기록입니다.</label><p class="error" id="test-error" role="alert"></p><div class="actions"><button class="primary" type="submit">저장하고 기준에 적용</button><button type="button" class="ghost" data-action="postpone" data-lift="${k}">점검 1주 미루기</button><button type="button" class="ghost" data-action="close-test">접기</button></div><details class="test-plan"><summary>재측정 날의 진행 순서</summary><ol><li>이전의 무리 없는 훈련 중량을 참고해 3~5회 세트를 계획합니다. 처음이라면 코치와 자세부터 확인하세요.</li><li>가벼운 전신 준비 뒤, 아래 계산기에 계획한 측정 세트 중량을 넣어 웜업을 확인합니다.</li><li>마지막 웜업 후 충분히 쉬고 1~2회 여유가 남는 선에서 3~5회 기록을 남깁니다. 예정 중량이 무거우면 줄입니다.</li><li>오늘의 해당 종목 고강도 세트를 대체하세요. 평소 볼륨에 측정을 추가하지 않습니다.</li></ol><label>계획한 3~5회 세트 중량 (kg)<input id="test-warm-kg" type="number" min="20" max="500" step="2.5" placeholder="이전 훈련 기록을 참고"></label><div id="test-warm-result"></div></details></form>`;
}
function showGuide(name){const g=G[name];if(!g)return;const source=g.source||(g.base&&G[g.base].source)||'https://www.acefitness.org/resources/everyone/exercise-library/';
$('guide-body').innerHTML=`<div class="helper">동작 가이드 · ${g.target}</div><h2 id="guide-title">${name}</h2><div class="helper">${g.en}</div><h3>이 순서로 해보세요</h3><ol>${g.steps.map(s=>`<li>${s}</li>`).join('')}</ol><p class="guide-cue">${g.cue}</p><h3>흔한 실수</h3><p>${g.avoid}</p><h3>어렵다면</h3><p>${g.easy}. 처음에는 가벼운 무게로 동작을 익히세요.</p><div class="sources"><a href="${source}" target="_blank" rel="noopener noreferrer">${g.source?'사진·설명 참고':'기본 동작 참고 · ACE'}</a><a href="https://www.youtube.com/results?search_query=${encodeURIComponent(g.en+' tutorial technique')}" target="_blank" rel="noopener noreferrer">시범 영상 찾기 ↗</a></div><p class="helper">영상 검색 결과는 별도 사이트에서 열립니다. 동작이 낯설면 코치에게 자세 확인을 요청하세요.</p>`;$('guide-dialog').showModal();}
function renderHistory(){
const ms=[...data.measurements].sort((a,b)=>a.date.localeCompare(b.date)||a.createdAt-b.createdAt);
const h=$('history');if(!ms.length){h.innerHTML='<h2>실제 기록의 변화</h2><div class="empty-record">아직 측정 기록이 없습니다. 첫 1RM 기록을 저장하면 날짜별 변화가 여기에 표시됩니다. 아래 로드맵은 목표 시나리오입니다.</div>';return;}
let graph='';const minDate=Math.min(...ms.map(m=>+C.date(m.date))),maxDate=Math.max(...ms.map(m=>+C.date(m.date))),max=Math.max(200,...ms.map(m=>m.value))*1.1;
const x=d=>48+((+C.date(d)-minDate)/Math.max(86400000,maxDate-minDate))*480,y=v=>200-v/max*160;
for(const k of Object.keys(names)){const rows=ms.filter(m=>m.lift===k);if(!rows.length)continue;graph+=`<polyline fill="none" stroke="${colors[k]}" stroke-width="2" points="${rows.map(m=>`${x(m.date)},${y(m.value)}`).join(' ')}"/>`+rows.map(m=>`<circle cx="${x(m.date)}" cy="${y(m.value)}" r="4" fill="${m.kind==='actual'?colors[k]:'var(--bg)'}" stroke="${colors[k]}" stroke-width="2"><title>${names[k]} ${m.date} ${m.value}kg ${m.kind==='actual'?'실측':'추정'}</title></circle>`).join('');}
h.innerHTML=`<h2>실제 기록의 변화</h2><div class="history-legend">${Object.keys(names).map(k=>`<span style="color:${colors[k]}">${names[k]}</span>`).join('')}<span>채움: 실측 · 빈 원: 추정</span></div><svg class="history-chart" viewBox="0 0 580 240" role="img" aria-label="날짜별 종목 기록. 아래 표에서 정확한 값을 확인할 수 있습니다."><path d="M48 24 V200 H540" fill="none" stroke="var(--line-strong)"/><text x="8" y="32" fill="var(--muted)" font-size="12">${Math.round(max)}kg</text><text x="24" y="205" fill="var(--muted)" font-size="12">0</text>${graph}<text x="48" y="228" fill="var(--muted)" font-size="12">${ms[0].date}</text><text x="540" y="228" text-anchor="end" fill="var(--muted)" font-size="12">${ms.at(-1).date}</text></svg><div class="history-table"><table><thead><tr><th>날짜</th><th>종목</th><th>기록</th><th>구분</th><th>입력 세트</th></tr></thead><tbody>${ms.slice(-12).reverse().map(m=>`<tr><td>${m.date}</td><td>${names[m.lift]}</td><td>${m.value}kg</td><td>${m.kind==='actual'?'실측':'추정'}</td><td>${m.kg}kg × ${m.reps}</td></tr>`).join('')}</tbody></table></div><p class="helper">최근 12개 기록 표시 · 추정값과 실측값을 구분해 비교하세요.</p>`;
}
function render(){document.querySelector('.brandsub').textContent=`빅3 합계 · 체중 ${T.read().bw}kg`;renderToday();renderAssessment();renderHistory();renderLog();addLegacyGuides();if(T.state.week===1&&latest('dl')){$('wBanner').textContent='현재 입력한 1RM 기준으로 계산합니다. 기록을 갱신하기 전 시작한 세션은 당시 계획 중량을 유지합니다.';}}
function addLegacyGuides(){document.querySelectorAll('#wDays .ex .n, #pane-plan .ex .n').forEach(el=>{if(el.querySelector('button'))return;const name=el.textContent;const aliases={'삼두 + 후면 삼각근':'삼두 푸시다운','컬, 케이블 로우, 복근':'덤벨 컬','인클라인 / 스포토 프레스':'인클라인 프레스'};if(G[name]||aliases[name])el.innerHTML=`<button class="ghost" style="text-align:left;padding:4px 0;border:0;text-decoration:underline;text-underline-offset:4px" data-guide="${aliases[name]||name}">${name}</button>`;});}
function renderLog(){let host=$('session-log');if(!host){host=document.createElement('section');host.id='session-log';host.className='assessment';$('assessment').after(host);}const rows=Object.entries(data.sessions).sort((a,b)=>b[1].date.localeCompare(a[1].date)||b[1].startedAt-a[1].startedAt).slice(0,8);host.innerHTML=`<h2>운동 기록</h2>${rows.length?rows.map(([key,s])=>`<div class="test-row"><div><strong>${s.date} · ${T.days[s.day].name}</strong><small>${s.completed?'완료':'기록 중'} · ${s.exercises.reduce((n,e)=>n+e.rows.filter(r=>r.done).length,0)}세트 기록</small></div><button class="ghost" data-action="open-log" data-key="${esc(key)}">열기</button></div>`).join(''):'<p>운동을 시작하면 세트 기록이 여기에 모입니다.</p>'}<button class="ghost" data-action="backup">기록 백업</button>`;}
function startTimer(seconds){timerEnd=Date.now()+seconds*1000;pausedSeconds=null;paintTimer();}
function paintTimer(){const h=$('rest-timer');if(timerEnd===null&&pausedSeconds===null){h.hidden=true;return;}h.hidden=false;const remain=pausedSeconds??Math.max(0,Math.ceil((timerEnd-Date.now())/1000));h.innerHTML=`<span>${pausedSeconds!==null?'일시정지':remain?'세트 사이 휴식':'휴식 완료'}</span><output aria-label="남은 휴식 시간">${String(Math.floor(remain/60)).padStart(2,'0')}:${String(remain%60).padStart(2,'0')}</output><button data-action="timer-pause">${pausedSeconds!==null?'계속':'정지'}</button><button data-action="timer-add">+30초</button><button data-action="timer-close">닫기</button>`;}
setInterval(paintTimer,1000);
document.addEventListener('click',event=>{const guide=event.target.closest('[data-guide]');if(guide){showGuide(guide.dataset.guide);return;}const b=event.target.closest('[data-action]');if(!b)return;const a=b.dataset.action;
if(a==='pick-day'){selected=+b.dataset.day;active=null;renderToday();}
if(a==='start')startSession(+b.dataset.day);
if(a==='close-session'){active=null;renderToday();}
if(a==='current-week')$('wToday').click();
if(a==='test'){testLift=b.dataset.lift;renderTest();$('test-editor').scrollIntoView({block:'nearest'});}
if(a==='close-test'){testLift=null;renderAssessment();}
if(a==='assessment'){$('tabWeek').click();$('assessment').scrollIntoView({block:'start'});}
if(a==='postpone'){const k=b.dataset.lift,d=C.due(latest(k)?.date,today(),data.postponed[k]);data.postponed[k]=C.add(d.date<today()?today():d.date,7);save();testLift=null;renderAssessment();}
if(a==='alternate'&&active){const s=data.sessions[active],e=s.exercises[+b.dataset.ex];if(e.rows.some(r=>r.done)){$('session-feedback').textContent='완료한 세트가 있는 동작은 바꿀 수 없습니다.';return;}[e.name,e.alternate]=[e.alternate,e.name];save();renderSession();}
if(a==='timer')startTimer(+b.dataset.seconds);
if(a==='timer-pause'){if(pausedSeconds===null){pausedSeconds=Math.max(0,Math.ceil((timerEnd-Date.now())/1000));timerEnd=null;}else{startTimer(pausedSeconds);}paintTimer();}
if(a==='timer-add'){if(pausedSeconds!==null)pausedSeconds+=30;else timerEnd=Math.max(Date.now(),timerEnd)+30000;paintTimer();}
if(a==='timer-close'){timerEnd=null;pausedSeconds=null;paintTimer();}
if(a==='finish'&&active){const s=data.sessions[active];if(s.date>today()){$('session-feedback').textContent='실제 운동일을 오늘 또는 과거 날짜로 바꿔주세요.';return;}if(s.exercises.some(e=>e.rows.some(r=>!r.done))){$('session-feedback').textContent='아직 완료하지 않은 세트가 있습니다. 실제 기록과 완료 체크를 확인하세요.';return;}s.completed=true;s.finishedAt=Date.now();if(save()){renderToday();renderLog();const peak=Math.max(...s.exercises.flatMap(e=>e.rows.map(r=>+r.rpe)));$('session-feedback').textContent=peak>=9?'운동 완료. RPE 9 이상인 세트가 있어 다음 동일 세션은 우선 같은 무게로 확인하세요.':'운동 완료! 다음 세션 전에 오늘의 기록과 컨디션을 확인하세요. 기준 중량은 자동으로 올리지 않습니다.';renderHistory();}}
if(a==='open-log'){active=b.dataset.key;renderSession();$('session-editor').scrollIntoView({block:'start'});}
if(a==='backup'){const blob=new Blob([JSON.stringify({training:data,baselines:T.read(),schedule:T.state},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=`3-500-records-${today()}.json`;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
});
document.addEventListener('change',event=>{const el=event.target;
if(el.id==='test-kind'){const actual=el.value==='actual';$('reps-label').hidden=actual;$('test-explanation').textContent=actual?'실제로 1회 성공한 기록만 입력합니다. 반복 세트의 추정값과 구분해서 저장됩니다.':'Epley: 중량 × (1 + 횟수 ÷ 30). 여유를 남긴 세트는 실제 최대치보다 낮을 수 있으며 오차를 보장하지 않습니다.';updateEstimate();}
if(el.id==='test-reps')updateEstimate();
if(el.id==='bar-weight'){data.bar=+el.value;if(active) for(const e of data.sessions[active].exercises)e.warm={};save();renderSession();}
if(!active)return;const s=data.sessions[active];
if(el.id==='session-date'){if(!C.date(el.value)||el.value>today()){el.value=s.date;$('session-feedback').textContent='오늘 또는 과거의 실제 운동일을 선택하세요.';return;}const key=`${el.value}:${s.day}`;if(key!==active&&data.sessions[key]){el.value=s.date;$('session-feedback').textContent='그 날짜에 같은 세션의 기록이 이미 있습니다.';return;}delete data.sessions[active];s.date=el.value;data.sessions[key]=s;active=key;save();renderLog();}
if(el.dataset.work!==undefined){if(el.value!==''&&!el.checkValidity()){el.reportValidity();return;}const e=s.exercises[+el.dataset.work];e.kg=el.value===''?null:+el.value;e.warm={};for(const r of e.rows)if(!r.done)r.kg=e.kg??'';save();const opened=[...document.querySelectorAll('.exercise')].map(d=>d.open);renderSession();document.querySelectorAll('.exercise').forEach((d,i)=>d.open=opened[i]);}
if(el.dataset.row){const [ei,ri,k]=el.dataset.row.split(':');if(!el.checkValidity()){el.reportValidity();return;}s.exercises[ei].rows[ri][k]=el.value===''?'':+el.value;s.exercises[ei].rows[ri].done=false;s.completed=false;const check=document.querySelector(`[data-done="${ei}:${ri}"]`);if(check)check.checked=false;save();updateCount();}
if(el.dataset.warm){const [ei,i]=el.dataset.warm.split(':');s.exercises[ei].warm[i]=el.checked;save();}
if(el.dataset.done){const [ei,ri]=el.dataset.done.split(':'),r=s.exercises[ei].rows[ri];if(el.checked&&(r.kg===''||r.reps===''||r.rpe===''||r.kg<0||r.kg>500||r.reps<1||r.reps>50||r.rpe<1||r.rpe>10)){el.checked=false;$('session-feedback').textContent='중량·횟수·RPE를 모두 입력한 뒤 완료하세요.';return;}r.done=el.checked;s.completed=false;save();updateCount();if(el.checked)startTimer(s.exercises[ei].main?180:90);}
});
function updateCount(){const s=data.sessions[active];if(!s)return;$('session-count').textContent=`${s.exercises.reduce((n,e)=>n+e.rows.filter(r=>r.done).length,0)} / ${s.exercises.reduce((n,e)=>n+e.rows.length,0)}세트`;}
function updateEstimate(){const kg=+$('test-kg').value,actual=$('test-kind').value==='actual',v=actual&&kg>0&&kg<=500?kg:C.estimate(kg,+$('test-reps').value);$('test-result').textContent=v?`${actual?'실측 1RM':'추정 e1RM'} ${v}kg`:'유효한 중량을 입력하세요';}
document.addEventListener('input',event=>{if(event.target.id==='test-kg')updateEstimate();if(event.target.id==='test-warm-kg'){const work=+event.target.value,rows=C.warmup(work,data.bar,testLift==='dl');$('test-warm-result').innerHTML=event.target.checkValidity()&&work>0?rows.map(r=>`<p>${r.kg}kg × ${r.reps}회 × 1세트 · 휴식 ${r.rest}초</p>`).join('')+'<p>마지막 웜업 뒤 2~4분 휴식. 계획한 세트가 무겁게 느껴지면 중량을 낮추세요.</p>':'유효한 중량을 입력하세요.';}});
document.addEventListener('submit',event=>{if(event.target.id!=='test-form')return;event.preventDefault();const date=$('test-date').value,kg=+$('test-kg').value,kind=$('test-kind').value,reps=kind==='actual'?1:+$('test-reps').value,value=kind==='actual'?kg:C.estimate(kg,reps);if(!C.date(date)||date>today()||!value||value<20||value>500){$('test-error').textContent='날짜와 중량을 확인하세요. 기준 1RM은 20~500kg 범위입니다.';return;}
const old=latest(testLift);data.measurements.push({lift:testLift,date,kind,kg,reps,value,createdAt:Date.now()});delete data.postponed[testLift];if(!old||date>=old.date)T.inputs[testLift].value=value;
if(!save()){$('test-error').textContent='기록을 브라우저에 저장하지 못했습니다. 기록을 백업하세요.';return;}testLift=null;T.render();render();});
document.addEventListener('training-render',()=>{if(active&&data.sessions[active]?.week!==T.state.week)active=null;render();});
// Surface any legacy storage failures without changing the original storage keys.
window.addEventListener('storage',event=>{if(event.key===KEY)status('다른 창에서 기록이 변경되었습니다. 현재 입력을 마친 뒤 새로고침하세요.');});
render();
})();
