(function(root){
  'use strict';
  const G = {
  "백스쿼트": {en:"Back Squat", target:"대퇴사두 · 둔근", sub:"척추기립근 · 복근 · 햄스트링", steps:["랙의 안전바를 설정하고 바를 목이 아닌 등 위에 얹으세요. 발바닥 전체로 지지합니다.", "배 둘레를 단단히 만든 채 무릎을 발끝 방향으로 굽히며 내려갑니다.", "몸통과 골반을 함께 올리며 바가 발 중앙 위에 머물게 합니다."], cue:"발끝보다 무릎을 살짝 바깥으로 밀며 내려간다", avoid:"무릎이 안으로 말리는 것 / 상체가 먼저 서면서 바가 앞으로 빠지는 것", easy:"맨몸 스쿼트 또는 가벼운 고블릿 스쿼트", why:"합계에서 여유가 가장 많은 종목. 남은 110kg 중 50kg이 여기서 나옵니다.", p:["quad", "glute"], s:["erector", "abs", "ham"], source:"https://www.acefitness.org/resources/everyone/exercise-library/"},
  "벤치프레스": {en:"Bench Press", target:"가슴 · 삼두", sub:"어깨(앞·옆)", steps:["안전바나 보조자를 확보하고 머리·등·엉덩이를 벤치에, 양발을 바닥에 둡니다.", "엄지를 감아 바를 잡고 손목 아래에 팔꿈치가 오도록 조절합니다. 가슴 쪽으로 천천히 내립니다.", "가슴에서 튕기지 않고 밀어 올립니다. 어깨가 앞으로 들리지 않게 합니다."], cue:"견갑을 모아 뒤로 내리고 그 자세를 끝까지 유지", avoid:"견갑이 풀리며 어깨가 앞으로 나오는 것 / 가슴에서 바운스로 튕기는 것", easy:"가벼운 덤벨 벤치프레스", why:"이미 최고 종목이라 상승분은 20kg만 배정했습니다. 대신 절대 빠뜨리면 안 됩니다.", p:["chest", "triceps"], s:["dfront"], source:"https://www.nasm.org/resource-center/exercise-library/barbell-bench-press"},
  "데드리프트": {en:"Deadlift", target:"척추기립근 · 둔근 · 햄스트링", sub:"광배근 · 승모근 · 전완 · 대퇴사두", steps:["바를 발 중앙 위에 놓고 정강이를 가까이 가져갑니다. 가벼운 원판은 받침으로 표준 높이를 맞춥니다.", "엉덩이를 접고 바를 잡습니다. 배와 등을 고정하고 바의 유격을 먼저 없앱니다.", "바를 몸 가까이 두고 바닥을 밀며 일어섭니다. 위에서 허리를 뒤로 과하게 젖히지 않습니다."], cue:"바는 정강이에 붙여 수직으로 올린다", avoid:"엉덩이가 먼저 올라가며 등이 말리는 것 / 바가 몸에서 떨어져 앞으로 나가는 것", easy:"높이를 올린 블록 데드리프트", why:"추정치 160에서 200까지 40kg. 첫 주에 무거운 3회로 실제 값부터 확인해야 합니다.", p:["erector", "glute", "ham"], s:["lat", "trap", "forearm", "quad"], source:"https://www.acefitness.org/continuing-education/certified/december-2024/8762/the-ace-do-it-better-series-the-deadlift/"},
  "루마니안 데드리프트": {en:"Romanian Deadlift", target:"햄스트링 · 둔근", sub:"척추기립근", steps:["선 자세에서 바를 허벅지 앞에 들고 무릎을 조금 굽힙니다.", "무릎 각도를 크게 바꾸지 않고 엉덩이를 뒤로 보냅니다. 바는 다리를 따라 내려갑니다.", "허리 모양을 유지할 수 있는 범위에서 멈춘 후 엉덩이를 앞으로 가져와 일어섭니다."], cue:"무릎 각도를 고정하고 엉덩이를 뒤로 보낸다", avoid:"스쿼트처럼 무릎을 접는 것 / 등을 말아서 더 내리려는 것", easy:"가벼운 덤벨 RDL", why:"데드리프트의 시작 구간을 담당하는 햄스트링·둔근을 허리 피로 없이 키웁니다.", p:["ham", "glute"], s:["erector"], source:"https://www.acefitness.org/continuing-education/certified/may-2025/8865/the-ace-do-it-better-series-the-romanian-deadlift/"},
  "레그 프레스": {en:"Leg Press", target:"대퇴사두 · 둔근", sub:"햄스트링", steps:["무릎이 90도 아래로 깊게 내려간다", "허리가 시트에서 뜨지 않는 범위까지만", "무릎을 완전히 잠그지 않는다"], cue:"무릎이 90도 아래로 깊게 내려간다", avoid:"너무 얕게 미는 것 / 골반이 말리며 허리가 뜨는 것", easy:"맨몸 스쿼트", why:"스쿼트로 허리를 더 태우지 않고 대퇴사두 볼륨만 추가합니다.", p:["quad", "glute"], s:["ham"], source:"https://www.acefitness.org/resources/everyone/exercise-library/"},
  "레그컬": {en:"Leg Curl", target:"햄스트링", sub:"종아리", steps:["기계 회전축과 무릎 관절을 맞추고 패드를 발목 바로 위에 둡니다.", "엉덩이를 고정하고 무릎을 굽힙니다.", "무게를 놓지 말고 천천히 원위치로 돌아갑니다."], cue:"골반을 패드에 붙여 고정", avoid:"반동으로 던지는 것 / 골반이 들리는 것", easy:"중량과 가동 범위 줄이기", why:"무릎을 지나는 햄스트링 기능. 스쿼트·데드 중량이 올라갈수록 부상 방지 값이 커집니다.", p:["ham"], s:["calf"], source:"https://www.acefitness.org/resources/everyone/exercise-library/"},
  "행잉 레그레이즈": {en:"Hanging Leg Raise", target:"복근", sub:"전완 · 광배근", steps:["골반을 말아 올리는 게 핵심이다 (다리만 드는 게 아니다)", "흔들림 없이 통제한다", "내릴 때 천천히"], cue:"골반을 말아 올리는 게 핵심이다 (다리만 드는 게 아니다)", avoid:"반동으로 몸을 흔드는 것 / 골반은 그대로 두고 다리만 드는 것", easy:"누워서 무릎 당기기", why:"스쿼트·데드에서 복압을 유지하는 능력이 곧 중량입니다.", p:["abs"], s:["forearm", "lat"], source:"https://www.acefitness.org/resources/everyone/exercise-library/"},
  "인클라인 덤벨 프레스": {en:"Incline Dumbbell Press", target:"가슴 · 어깨(앞·옆)", sub:"삼두", steps:["견갑을 모아 고정", "덤벨은 가슴 위쪽 라인으로", "팔꿈치를 몸통에서 45도 정도로"], cue:"견갑을 모아 고정", avoid:"경사를 너무 높여 어깨 운동이 되는 것 / 맨 위에서 덤벨을 부딪히는 것", easy:"가벼운 덤벨 또는 머신 인클라인 프레스", why:"벤치의 상부 가슴 약점을 메웁니다. 벤치 정체 구간에서 가장 효과가 큽니다.", p:["chest", "dfront"], s:["triceps"], source:"https://www.acefitness.org/resources/everyone/exercise-library/"},
  "중량 딥스": {en:"Weighted Dip", target:"가슴 · 삼두", sub:"어깨(앞·옆)", steps:["상체를 살짝 앞으로 기울여 가슴에 싣는다", "어깨가 팔꿈치보다 살짝 아래까지", "어깨를 으쓱하지 않는다"], cue:"상체를 살짝 앞으로 기울여 가슴에 싣는다", avoid:"너무 깊게 내려 어깨 앞이 눌리는 것 / 반동으로 튕겨 올라오는 것", easy:"벤치 딥스 또는 어시스트 딥스", why:"삼두와 가슴 하부를 동시에. 벤치 락아웃 구간에 직접 반영됩니다.", p:["chest", "triceps"], s:["dfront"], source:"https://www.acefitness.org/resources/everyone/exercise-library/"},
  "케이블 플라이": {en:"Cable Fly", target:"가슴", sub:"어깨(앞·옆)", steps:["팔꿈치 각도를 살짝 굽힌 채 고정", "모으는 지점에서 1초", "가벼운 무게로 범위를 크게"], cue:"팔꿈치 각도를 살짝 굽힌 채 고정", avoid:"프레스처럼 팔을 펴고 미는 것 / 무게를 올려 어깨로 끌어오는 것", easy:"가벼운 무게로 같은 동작", why:"프레스로 채우기 힘든 가슴 신장 구간 볼륨입니다.", p:["chest"], s:["dfront"], source:"https://www.acefitness.org/resources/everyone/exercise-library/"},
  "삼두 푸시다운": {en:"Triceps Pushdown", target:"삼두", sub:"", steps:["케이블 앞에 서서 팔꿈치를 옆구리 가까이 둡니다.", "윗팔을 고정하고 팔꿈치를 펴서 손잡이를 내립니다.", "팔꿈치 위치를 유지하며 천천히 되돌립니다."], cue:"팔꿈치를 몸통에 붙여 고정", avoid:"팔꿈치가 앞뒤로 움직이는 것 / 어깨로 눌러 내리는 것", easy:"가벼운 밴드 푸시다운", why:"벤치 상단 락아웃은 삼두가 만듭니다.", p:["triceps"], s:[], source:"https://www.acefitness.org/resources/everyone/exercise-library/"},
  "바벨 로우": {en:"Barbell Row", target:"광배근 · 승모근", sub:"이두 · 척추기립근 · 어깨(뒤)", steps:["엉덩이를 접고 무릎을 약간 굽혀 몸통을 기울입니다.", "몸통 각도를 유지하며 바를 몸 쪽으로 당깁니다.", "어깨를 으쓱하지 않고 팔을 천천히 폅니다."], cue:"상체 각도를 45도 이하로 고정", avoid:"상체를 세우며 반동으로 당기는 것 / 등이 말리는 것", easy:"가슴 지지 덤벨 로우", why:"데드리프트에서 바를 몸에 붙이는 힘이 여기서 나옵니다.", p:["lat", "trap"], s:["biceps", "erector", "dback"], source:"https://www.catalystathletics.com/exercise/171/Bent-Row/"},
  "랫풀다운": {en:"Lat Pulldown", target:"광배근", sub:"이두 · 어깨(뒤)", steps:["허벅지 패드를 고정하고 바를 잡습니다.", "가슴을 편 상태에서 팔꿈치를 아래로 내려 바를 윗가슴 쪽으로 당깁니다.", "몸을 크게 흔들지 않고 천천히 되돌립니다."], cue:"가슴을 세우고 쇄골 쪽으로 당긴다", avoid:"몸을 뒤로 눕혀 반동 쓰는 것 / 팔로만 당기는 것", easy:"가벼운 중립그립 랫풀다운", why:"광배 크기는 벤치 안정성과 데드 락아웃 모두에 영향을 줍니다.", p:["lat"], s:["biceps", "dback"], source:"https://www.acefitness.org/resources/everyone/exercise-library/"},
  "시티드 케이블 로우": {en:"Seated Cable Row", target:"광배근 · 승모근", sub:"이두", steps:["상체는 세운 채 고정", "견갑을 모으고 1초", "늘릴 때 등이 말리지 않게"], cue:"상체는 세운 채 고정", avoid:"상체를 앞뒤로 흔드는 것 / 어깨가 으쓱 올라가는 것", easy:"밴드 로우", why:"중간 등 두께. 바벨 로우보다 허리 부담 없이 볼륨을 채웁니다.", p:["lat", "trap"], s:["biceps"], source:"https://www.acefitness.org/resources/everyone/exercise-library/"},
  "바벨 컬": {en:"Barbell Curl", target:"이두", sub:"전완", steps:["팔꿈치를 몸통 옆에 고정", "내릴 때 3초", "손목을 꺾지 않는다"], cue:"팔꿈치를 몸통 옆에 고정", avoid:"허리로 반동 주는 것 / 팔꿈치가 앞으로 나가는 것", easy:"덤벨 컬", why:"로우·풀 계열에서 팔이 먼저 지치지 않게 합니다.", p:["biceps"], s:["forearm"], source:"https://www.acefitness.org/resources/everyone/exercise-library/"},
  "포즈 / 스포토 벤치": {en:"Paused / Spoto Press", target:"가슴 · 삼두", sub:"어깨(앞·옆)", steps:["멈춤 구간에서 긴장을 풀지 않는다", "1~2초 완전 정지 후 폭발적으로", "무게는 메인의 65%"], cue:"멈춤 구간에서 긴장을 풀지 않는다", avoid:"멈춘 척만 하고 바운스로 넘어가는 것 / 무게를 메인 수준까지 올리는 것", easy:"가벼운 무게로 1초 정지 벤치", why:"시합 벤치는 정지 후 미는 동작입니다. 이 주 2회차 노출이 벤치 정체를 깹니다.", p:["chest", "triceps"], s:["dfront"], source:"https://www.acefitness.org/resources/everyone/exercise-library/"},
  "오버헤드 프레스": {en:"Overhead Press", target:"어깨(앞·옆)", sub:"삼두 · 승모근 · 복근", steps:["바를 쇄골 앞에 두고 발과 배를 단단히 고정합니다.", "턱을 살짝 뒤로 빼고 바를 머리 위로 밀어 올립니다.", "바가 머리를 지나면 몸 위로 정렬하고 통제하며 내립니다."], cue:"갈비뼈를 닫고 엉덩이·복근으로 몸통을 잠근다", avoid:"허리를 젖혀서 미는 것 / 바가 얼굴 앞으로 돌아 나가는 것", easy:"앉아서 가벼운 덤벨 프레스", why:"어깨와 삼두, 그리고 벤치를 받치는 상체 안정성.", p:["dfront"], s:["triceps", "trap", "abs"], source:"https://www.acefitness.org/resources/everyone/exercise-library/"},
  "사이드 레터럴 레이즈": {en:"Lateral Raise", target:"어깨(앞·옆)", sub:"승모근", steps:["팔꿈치를 살짝 굽힌 채 어깨 높이까지", "새끼손가락이 살짝 위로", "가볍게 15회"], cue:"팔꿈치를 살짝 굽힌 채 어깨 높이까지", avoid:"반동으로 던지는 것 / 승모근이 먼저 올라가는 것", easy:"밴드 사이드 레이즈", why:"어깨 폭. 무겁게 할 필요가 전혀 없는 종목입니다.", p:["dfront"], s:["trap"], source:"https://www.acefitness.org/resources/everyone/exercise-library/"},
  "페이스풀": {en:"Face Pull", target:"어깨(뒤)", sub:"승모근", steps:["로프를 얼굴 높이에 맞추고 안정적으로 섭니다.", "팔꿈치를 옆으로 벌리며 로프 양끝을 얼굴 옆으로 당깁니다.", "어깨를 으쓱하지 않고 통제하며 되돌립니다."], cue:"손이 귀 옆으로 오게 당긴다", avoid:"무겁게 해서 로우가 되는 것 / 팔꿈치가 아래로 처지는 것", easy:"가벼운 밴드 페이스풀", why:"벤치 볼륨이 늘수록 어깨 앞이 말립니다. 그걸 되돌리는 유지보수 종목입니다.", p:["dback"], s:["trap"], source:"https://www.acefitness.org/resources/everyone/exercise-library/"},
  "삼두 + 이두 슈퍼셋": {en:"Triceps + Biceps Superset", target:"삼두 · 이두", sub:"전완", steps:["두 종목 사이에는 휴식 없이", "세트 사이만 90초", "무게보다 수축에 집중"], cue:"두 종목 사이에는 휴식 없이", avoid:"무게 욕심으로 반동 쓰는 것", easy:"두 종목을 쉬면서 따로 수행", why:"짧은 시간에 팔 볼륨. 벤치와 로우 양쪽의 보조 근육입니다.", p:["triceps", "biceps"], s:["forearm"], source:"https://www.acefitness.org/resources/everyone/exercise-library/"},
  "프론트 스쿼트": {en:"Front Squat", target:"대퇴사두", sub:"복근 · 척추기립근 · 둔근", steps:["바를 손목이 아닌 어깨 앞쪽에 받치고 팔꿈치를 올립니다.", "몸통을 세우고 무릎을 발끝 방향으로 보내며 앉습니다.", "팔꿈치 높이를 유지하며 발바닥 전체로 밀고 일어섭니다."], cue:"팔꿈치를 최대한 높게 유지", avoid:"팔꿈치가 떨어지며 바가 앞으로 굴러가는 것 / 상체가 숙여지는 것", easy:"고블릿 스쿼트", why:"백스쿼트에서 상체가 숙여지는 문제를 직접 고칩니다. 스쿼트 2회차 노출.", p:["quad"], s:["abs", "erector", "glute"], source:"https://www.acefitness.org/resources/everyone/exercise-library/"},
  "데피싯 데드리프트": {en:"Deficit Deadlift", target:"척추기립근 · 둔근 · 햄스트링", sub:"대퇴사두 · 광배근", steps:["일반 데드리프트가 익숙할 때 낮고 안정적인 발판 위에 섭니다.", "더 낮은 바를 잡아도 허리와 몸통을 유지할 수 있는지 먼저 확인합니다.", "바를 몸 가까이 두고 다리로 바닥을 밀며 일어섭니다."], cue:"가동범위가 늘어난 만큼 무게는 메인의 60%", avoid:"무게 욕심으로 등이 말리는 것 / 판을 너무 높게 쓰는 것", easy:"일반 데드리프트", why:"데드리프트 바닥 구간이 약점이면 여기서 고쳐집니다. 데드 2회차 노출.", p:["erector", "glute", "ham"], s:["quad", "lat"], source:"https://www.acefitness.org/resources/everyone/exercise-library/"},
  "불가리안 스플릿 스쿼트": {en:"Bulgarian Split Squat", target:"대퇴사두 · 둔근", sub:"햄스트링", steps:["뒷발을 낮은 벤치에 걸치고 앞발은 균형 잡히는 거리에 둡니다.", "앞무릎을 발끝 방향으로 굽히며 수직으로 내려갑니다.", "앞발로 바닥을 밀어 올라옵니다. 양쪽을 각각 수행합니다."], cue:"앞발에 체중 80%", avoid:"뒷다리로 밀어내는 것 / 보폭이 너무 좁은 것", easy:"맨몸 스플릿 스쿼트", why:"좌우 불균형 교정. 스쿼트 정체의 절반은 한쪽 다리가 약해서 생깁니다.", p:["quad", "glute"], s:["ham"], source:"https://www.acefitness.org/resources/everyone/exercise-library/"},
  "힙 쓰러스트": {en:"Hip Thrust", target:"둔근", sub:"햄스트링", steps:["턱을 당겨 시선을 앞으로", "락아웃에서 1초 조이기", "허리로 젖히지 않고 골반만 민다"], cue:"턱을 당겨 시선을 앞으로", avoid:"허리를 젖혀 각도를 만드는 것 / 가동범위를 반만 쓰는 것", easy:"바닥에서 하는 글루트 브리지", why:"데드리프트 락아웃과 스쿼트 상승 구간의 둔근 출력.", p:["glute"], s:["ham"], source:"https://www.acefitness.org/resources/everyone/exercise-library/"},
  "앱 롤아웃": {en:"Ab Wheel Rollout", target:"복근", sub:"광배근 · 척추기립근", steps:["매트에 무릎을 대고 휠을 어깨 아래에 놓습니다.", "복부에 힘을 주고 허리가 꺾이지 않는 범위까지만 앞으로 밉니다.", "몸통을 유지하며 시작점으로 돌아옵니다."], cue:"허리가 꺾이지 않는 범위까지만", avoid:"허리를 꺾으면서 더 나가는 것 / 반동으로 돌아오는 것", easy:"짧은 범위 롤아웃 또는 플랭크", why:"안티 익스텐션. 데드리프트에서 등이 말리지 않게 하는 직접적인 능력입니다.", p:["abs"], s:["lat", "erector"], source:"https://www.acefitness.org/resources/everyone/exercise-library/"},
  "레그 익스텐션": {en:"Leg Extension", target:"대퇴사두", sub:"", steps:["끝까지 펴서 1초 조인다", "내릴 때 3초에 걸쳐 천천히", "골반이 시트에서 뜨지 않게"], cue:"끝까지 펴서 1초 조인다", avoid:"반동으로 차 올리는 것 / 가동범위를 반만 쓰는 것", easy:"앉아서 무릎 펴기(무중량)", why:"스쿼트로는 채우기 힘든 대퇴직근 볼륨. 다리 굵기가 곧 스쿼트 잠재력입니다.", p:["quad"], s:[], source:"https://www.acefitness.org/resources/everyone/exercise-library/"},
  "라잉 레그컬": {en:"Lying Leg Curl", target:"햄스트링", sub:"종아리", steps:["골반을 패드에 눌러 고정", "수축에서 1초 멈춤", "내릴 때 천천히"], cue:"골반을 패드에 눌러 고정", avoid:"골반이 들리는 것 / 반동으로 던지는 것", easy:"누워서 햄스트링 브리지", why:"주 2회차 햄스트링 노출. 데드리프트 볼륨은 늘리지 않고 근육만 키웁니다.", p:["ham"], s:["calf"], source:"https://www.acefitness.org/resources/everyone/exercise-library/"},
  "스탠딩 카프 레이즈": {en:"Standing Calf Raise", target:"종아리", sub:"", steps:["뒤꿈치를 최대한 아래로 내렸다가 최대한 위로", "맨 위에서 1초 조이기", "반동 없이 통제"], cue:"뒤꿈치를 최대한 아래로 내렸다가 최대한 위로", avoid:"가동범위를 반만 쓰는 것 / 무릎을 굽혀 반동 주는 것", easy:"맨몸 뒤꿈치 들기", why:"종아리는 스쿼트·데드에서 발목 안정성을 담당하는데 이 프로그램에 유일하게 비어 있던 부위입니다.", p:["calf"], s:[], source:"https://www.acefitness.org/resources/everyone/exercise-library/"},
  "시티드 카프 레이즈": {en:"Seated Calf Raise", target:"종아리", sub:"", steps:["무릎 90도 고정", "아래로 완전히 늘렸다가 위로 완전히", "15회를 천천히"], cue:"무릎 90도 고정", avoid:"빠르게 튕기는 것 / 무게만 올리고 범위를 줄이는 것", easy:"맨몸 뒤꿈치 들기", why:"스탠딩과 각도가 달라 다른 근육을 씁니다. 둘 다 해야 종아리가 큽니다.", p:["calf"], s:[], source:"https://www.acefitness.org/resources/everyone/exercise-library/"},
  "오버헤드 케이블 익스텐션": {en:"Overhead Cable Extension", target:"삼두", sub:"", steps:["팔꿈치를 귀 옆에 고정", "머리 뒤에서 완전히 늘린다", "끝까지 펴서 1초"], cue:"팔꿈치를 귀 옆에 고정", avoid:"팔꿈치가 벌어지는 것 / 허리를 젖혀 미는 것", easy:"가벼운 덤벨 오버헤드 익스텐션", why:"삼두 장두는 팔이 머리 위에 있을 때만 제대로 늘어납니다. 푸시다운만으로는 안 됩니다.", p:["triceps"], s:[], source:"https://www.acefitness.org/resources/everyone/exercise-library/"},
  "원암 덤벨 로우": {en:"One-Arm Dumbbell Row", target:"광배근", sub:"이두 · 승모근", steps:["팔꿈치를 골반 쪽으로 당긴다", "아래에서 광배를 완전히 늘린다", "상체를 비틀지 않는다"], cue:"팔꿈치를 골반 쪽으로 당긴다", avoid:"몸통을 회전시켜 반동 쓰는 것 / 팔로만 당기는 것", easy:"가벼운 무게로 같은 동작", why:"좌우 따로 하니 약한 쪽이 드러납니다. 데드리프트 그립 불균형의 원인이 여기입니다.", p:["lat"], s:["biceps", "trap"], source:"https://www.acefitness.org/resources/everyone/exercise-library/"},
  "인클라인 덤벨 컬": {en:"Incline Dumbbell Curl", target:"이두", sub:"전완", steps:["팔을 완전히 늘어뜨린 상태에서 시작", "팔꿈치를 뒤에 고정", "내릴 때 3초"], cue:"팔을 완전히 늘어뜨린 상태에서 시작", avoid:"팔꿈치가 앞으로 나오는 것 / 반동으로 올리는 것", easy:"서서 하는 덤벨 컬", why:"이두 장두가 최대로 늘어난 상태에서 수축시킵니다. 바벨 컬과 자극이 다릅니다.", p:["biceps"], s:["forearm"], source:"https://www.acefitness.org/resources/everyone/exercise-library/"},
  "리어 델트 플라이": {en:"Rear Delt Fly", target:"어깨(뒤)", sub:"승모근", steps:["팔꿈치를 살짝 굽힌 채 고정", "견갑을 모으지 말고 팔만 벌린다", "가볍게", "15회"], cue:"팔꿈치를 살짝 굽힌 채 고정", avoid:"무겁게 해서 로우가 되는 것 / 승모근으로 으쓱하는 것", easy:"밴드 리어 델트 풀", why:"벤치 볼륨이 늘수록 어깨가 앞으로 말립니다. 페이스풀과 함께 자세를 되돌립니다.", p:["dback"], s:["trap"], source:"https://www.acefitness.org/resources/everyone/exercise-library/"},
  "케이블 크런치": {en:"Cable Crunch", target:"복근", sub:"", steps:["고관절이 아니라 척추를 마는 동작", "수축에서 1초", "골반은 고정"], cue:"고관절이 아니라 척추를 마는 동작", avoid:"고관절만 접었다 펴는 것 / 팔로 당기는 것", easy:"가벼운 무게로 같은 동작", why:"중량을 실을 수 있는 유일한 복근 운동. 복압 강도가 곧 스쿼트·데드 중량입니다.", p:["abs"], s:[], source:"https://www.acefitness.org/resources/everyone/exercise-library/"},
  "머신 체스트 프레스": {en:"Machine Chest Press", target:"가슴 · 삼두", sub:"어깨(앞·옆)", steps:["손잡이가 가슴 중간 높이에 오게 시트를 맞춘다", "견갑을 등받이에 눌러 고정", "마지막 세트는 무게를 25% 내려 실패까지 (드롭세트)"], cue:"손잡이가 가슴 중간 높이에 오게 시트를 맞춘다", avoid:"시트가 너무 높아 어깨 운동이 되는 것 / 팔을 완전히 잠가 장력을 푸는 것", easy:"가벼운 푸시업", why:"프리웨이트로는 무서워서 못 미는 지점까지 밀 수 있습니다. 가슴이 고민이면 이 종목에서 가장 많이 벌 수 있습니다.", p:["chest", "triceps"], s:["dfront"], source:"https://www.acefitness.org/resources/everyone/exercise-library/"},
  "인클라인 케이블 플라이": {en:"Incline Cable Fly", target:"가슴", sub:"어깨(앞·옆)", steps:["케이블을 낮은 위치에 걸고 위로 모은다", "팔꿈치 각도 고정", "모으는 지점에서 1초", "늘어나는 구간에서 천천히"], cue:"케이블을 낮은 위치에 걸고 위로 모은다", avoid:"프레스처럼 미는 것 / 무게를 올려 어깨로 끌어오는 것", easy:"가벼운 덤벨 플라이", why:"상부 가슴은 벤치만으로는 잘 안 붙습니다. 쇄골 아래가 비어 보이는 문제를 여기서 고칩니다.", p:["chest"], s:["dfront"], source:"https://www.acefitness.org/resources/everyone/exercise-library/"},
  "체스트 서포티드 로우": {en:"Chest-Supported Row", target:"광배근 · 승모근", sub:"이두 · 어깨(뒤)", steps:["가슴을 패드에서 떼지 않는다", "팔꿈치를 뒤로 보내며 견갑을 모은다", "수축에서 1초"], cue:"가슴을 패드에서 떼지 않는다", avoid:"가슴을 떼며 반동 쓰는 것 / 팔로만 당기는 것", easy:"가벼운 덤벨 로우", why:"데드리프트 다음날 허리 부담 없이 등 두께만 쌓습니다. 바벨 로우가 못 하는 역할입니다.", p:["lat", "trap"], s:["biceps", "dback"], source:"https://www.acefitness.org/resources/everyone/exercise-library/"},
  "스트레이트암 풀다운": {en:"Straight-Arm Pulldown", target:"광배근", sub:"복근", steps:["팔꿈치를 살짝 굽힌 채 끝까지 고정", "광배로만 내린다 (삼두로 미는 게 아니다)", "위에서 완전히 늘린다"], cue:"팔꿈치를 살짝 굽힌 채 끝까지 고정", avoid:"팔꿈치를 굽혔다 펴며 삼두 운동이 되는 것 / 상체를 세웠다 숙였다 하는 것", easy:"밴드 풀오버", why:"이두가 개입하지 않는 유일한 광배 운동. 등 날 마지막에 광배만 태워서 마무리합니다.", p:["lat"], s:["abs"], source:"https://www.acefitness.org/resources/everyone/exercise-library/"},
  "바벨 슈러그": {en:"Barbell Shrug", target:"승모근", sub:"전완", steps:["맨 위에서 1초 멈춘다", "어깨를 돌리지 말고 수직으로만", "스트랩을 써서 악력이 먼저 풀리지 않게"], cue:"맨 위에서 1초 멈춘다", avoid:"가동범위를 반만 쓰는 것 / 어깨를 회전시키는 것", easy:"덤벨 슈러그", why:"승모근은 데드리프트 락아웃을 버티는 근육입니다. 상체 실루엣도 여기서 결정됩니다.", p:["trap"], s:["forearm"], source:"https://www.acefitness.org/resources/everyone/exercise-library/"},
  "덤벨 숄더 프레스": {en:"Dumbbell Shoulder Press", target:"어깨(앞·옆)", sub:"삼두 · 승모근", steps:["덤벨을 귀 옆 높이까지 내린다", "손목이 팔꿈치 위에 수직으로", "맨 위에서 부딪히지 않는다"], cue:"덤벨을 귀 옆 높이까지 내린다", avoid:"너무 얕게 내리는 것 / 허리를 젖혀 미는 것", easy:"머신 숄더 프레스", why:"바벨 OHP보다 가동범위가 크고 좌우를 따로 씁니다. 어깨 볼륨의 핵심 한 종목.", p:["dfront"], s:["triceps", "trap"], source:"https://www.acefitness.org/resources/everyone/exercise-library/"},
  "케이블 사이드 레터럴": {en:"Cable Lateral Raise", target:"어깨(앞·옆)", sub:"승모근", steps:["케이블이 몸 뒤를 지나게 서서 아래에서부터 장력을 받는다", "어깨 높이까지", "반동 없이", "마지막 세트는 무게를 두 번 내려 3단 드롭세트"], cue:"케이블이 몸 뒤를 지나게 서서 아래에서부터 장력을 받는다", avoid:"무겁게 해서 승모근으로 들어올리는 것 / 상체를 흔드는 것", easy:"덤벨 사이드 레이즈", why:"덤벨은 맨 아래에서 장력이 0이지만 케이블은 처음부터 끝까지 걸립니다. 어깨 폭은 이 종목이 만듭니다.", p:["dfront"], s:["trap"], source:"https://www.acefitness.org/resources/everyone/exercise-library/"},
  "모빌리티 (고관절·흉추·발목)": {en:"Mobility Work", target:"척추기립근 · 둔근", sub:"햄스트링 · 종아리", steps:["고관절: 90/90", "카우치 스트레치", "흉추: 폼롤러 신전", "오픈북", "발목: 벽에 무릎 밀기 (뒤꿈치 고정)"], cue:"고관절: 90/90", avoid:"반동으로 튕기는 것 / 아픈 지점까지 밀어붙이는 것", easy:"가벼운 스트레칭", why:"스쿼트 깊이와 데드 시작 자세는 힘이 아니라 가동범위 문제인 경우가 많습니다.", p:["erector", "glute"], s:["ham", "calf"], source:"https://www.acefitness.org/resources/everyone/exercise-library/"},
  "플랭크 + 레그레이즈": {en:"Plank + Leg Raise", target:"복근", sub:"척추기립근 · 둔근", steps:["플랭크는 골반을 살짝 말아 60초", "레그레이즈는 허리를 바닥에 붙인 채", "호흡을 멈추지 않는다"], cue:"플랭크는 골반을 살짝 말아 60초", avoid:"플랭크에서 엉덩이가 뜨거나 처지는 것 / 레그레이즈에서 허리가 뜨는 것", easy:"무릎 대고 플랭크", why:"훈련하지 않는 이틀 동안 코어만은 유지합니다.", p:["abs"], s:["erector", "glute"], source:"https://www.acefitness.org/resources/everyone/exercise-library/"},
  };
  /* FSL(First Set Last) — 메인 종목의 첫 세트 무게로 5×5. 동작은 메인과 같다. */
  [['백스쿼트 (FSL)','백스쿼트'],['벤치프레스 (FSL)','벤치프레스'],['데드리프트 (FSL)','데드리프트'],['오버헤드 프레스 (FSL)','오버헤드 프레스']].forEach(function(p){
    if (!G[p[1]]) return;
    G[p[0]] = Object.assign({}, G[p[1]], {
      why: 'FSL(First Set Last) — 메인 세트가 끝난 뒤 첫 세트 무게로 돌아와 5회씩 반복합니다. 5/3/1은 무거운 세트가 적은 대신 여기서 볼륨을 채웁니다. 바 속도가 빠르게 유지되는 무게입니다.'
    });
  });
  if (G['오버헤드 프레스']) G['오버헤드 프레스'].why = '목요일 5/3/1 메인 종목. 어깨 전체와 삼두, 그리고 벤치를 받치는 상체 안정성을 만듭니다.';
  if (typeof module !== 'undefined' && module.exports) module.exports = G;
  else root.ExerciseGuides = G;
})(typeof window !== 'undefined' ? window : globalThis);
