const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const C=require('../core.js');
const {JSDOM}=require('jsdom');
const dir=path.join(__dirname,'..');
function boot(storage={}){const dom=new JSDOM(fs.readFileSync(path.join(dir,'index.html'),'utf8'),{url:'https://example.test',runScripts:'outside-only'});const w=dom.window;w.HTMLElement.prototype.scrollIntoView=function(){};w.HTMLDialogElement.prototype.showModal=function(){this.open=true;};for(const [k,v] of Object.entries(storage))w.localStorage.setItem(k,JSON.stringify(v));for(const file of ['core.js','guides.js','legacy.js','app.js'])w.eval(fs.readFileSync(path.join(dir,file),'utf8'));return dom;}
function click(w,s){const el=w.document.querySelector(s);assert.ok(el,'Missing '+s);el.click();}
function change(w,s,value){const el=w.document.querySelector(s);assert.ok(el,'Missing '+s);el.value=value;el.dispatchEvent(new w.Event('change',{bubbles:true}));}
test('warmups stay below work, use loadable steps and handle light bars',()=>{assert.deepEqual(C.warmup(90).map(x=>[x.kg,x.reps]),[[20,8],[35,5],[52.5,3],[70,1]]);assert.deepEqual(C.warmup(20),[]);for(const bar of [15,20])for(let kg=bar;kg<=300;kg+=2.5){const r=C.warmup(kg,bar);assert.ok(r.every((x,i)=>x.kg<kg&&x.kg>=bar&&x.kg%2.5===0&&(!i||x.kg>r[i-1].kg)));}assert.equal(C.warmup(112.5,20,true)[0].kg,40);});
test('valid dates, 8-week review and postponement',()=>{assert.equal(C.date('2026-02-30'),null);assert.equal(C.add('2026-12-20',56),'2027-02-14');assert.equal(C.due('2026-09-11','2026-09-11').date,'2026-11-06');assert.equal(C.due('2026-09-11','2026-11-07').overdue,true);assert.equal(C.due(null,'2026-09-11').unknown,true);assert.equal(C.due(null,'2026-09-11','2026-09-18').days,7);});
test('estimate validation and deload prescriptions',()=>{assert.equal(C.estimate(145,3),159.5);assert.equal(C.estimate(0,3),null);assert.equal(C.estimate(100,1),null);const p=C.prescription({main:'sq'}, {scheme:'2 × 5',pct:.55},4,{sq:130});assert.deepEqual(p,{kg:72.5,sets:2,reps:5});assert.deepEqual(C.prescription({s:'4 × 6',pct:.7,of:'bp'},{},4,{bp:100}),{kg:60,sets:2,reps:6});});
test('legacy values migrate without overwriting and tabs default to training',()=>{const dom=boot({'bigthree500.v1':{sq:150,bp:110,dl:180,bw:80}}),w=dom.window;try{assert.equal(w.Training.read().sq,150);assert.equal(w.document.getElementById('pane-week').hidden,false);assert.match(w.document.getElementById('today').textContent,/운동 시작/);assert.equal(w.document.getElementById('rTotal').textContent,'440');w.Training.goWeek(101);assert.match(w.document.getElementById('wLifts').textContent,/기준 1RM 150kg/);}finally{w.close();}});
test('session set saves and restores, rejects blank RPE, guide opens',()=>{const dom=boot(),w=dom.window;try{click(w,'[data-action="pick-day"][data-day="0"]');click(w,'[data-action="start"]');click(w,'[data-done="0:0"]');assert.equal(w.document.querySelector('[data-done="0:0"]').checked,false);change(w,'[data-row="0:0:rpe"]','8');click(w,'[data-done="0:0"]');assert.equal(w.document.querySelector('[data-done="0:0"]').checked,true);const data=JSON.parse(w.localStorage.getItem('bigthree500.training.v2'));assert.equal(Object.values(data.sessions)[0].exercises[0].rows[0].rpe,8);click(w,'[data-guide="백스쿼트"]');assert.equal(w.document.getElementById('guide-dialog').open,true);assert.match(w.document.getElementById('guide-body').textContent,/흔한 실수/);const next=boot({'bigthree500.training.v2':data});try{click(next.window,'[data-action="pick-day"][data-day="0"]');click(next.window,'[data-action="start"]');assert.equal(next.window.document.querySelector('[data-done="0:0"]').checked,true);}finally{next.window.close();}}finally{w.close();}});
test('assessment saves actual vs estimate, updates baseline and due date',()=>{const dom=boot(),w=dom.window;try{click(w,'[data-action="test"][data-lift="dl"]');change(w,'#test-kg','145');change(w,'#test-reps','3');w.document.getElementById('test-form-check').checked=true;w.document.getElementById('test-form').dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));assert.equal(w.Training.read().dl,159.5);const data=JSON.parse(w.localStorage.getItem('bigthree500.training.v2'));assert.equal(data.measurements[0].kind,'estimate');assert.match(w.document.getElementById('assessment').textContent,/56일 남음/);assert.match(w.document.getElementById('history').textContent,/추정/);click(w,'[data-action="test"][data-lift="sq"]');change(w,'#test-kind','actual');change(w,'#test-kg','140');w.document.getElementById('test-form-check').checked=true;w.document.getElementById('test-form').dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));assert.equal(w.Training.read().sq,140);assert.match(w.document.getElementById('history').textContent,/실측/);}finally{w.close();}});
test('all expanded exercises have guides and no duplicate IDs',()=>{const dom=boot(),w=dom.window;try{const ids=[...w.document.querySelectorAll('[id]')].map(e=>e.id);assert.equal(new Set(ids).size,ids.length);for(let i=0;i<4;i++){click(w,`[data-action="pick-day"][data-day="${i}"]`);click(w,'[data-action="start"]');const data=JSON.parse(w.localStorage.getItem('bigthree500.training.v2'));for(const e of Object.values(data.sessions).at(-1).exercises)assert.ok(w.ExerciseGuides[e.name],e.name);}}finally{w.close();}});
